--- #YAML:1.0
name                        : Math-GMP
version                     : 2.07
abstract                    : High speed arbitrary size integer math
author:              
  - Chip Turner <cturner@pattern.net>
  - Tels <tels@bloodgate.com>
  - Greg Sabino Mullane <greg@turnstep.com>

license                     : gpl
distribution_type           : module
dynamic_config              : 1

build_requires:
  Test::More                : 0.61
recommends:
  File::Comments            : 0
  Module::Signature         : 0.50
  Perl::Critic              : 0
  Pod::Spell                : 0
  Test::Pod                 : 0.95
  Test::Pod::Coverage       : 0
  Test::YAML::Meta          : 0.03
  Text::SpellChecker        : 0

provides:
  Math::GMP:
    file                    : GMP.pm
    version                 : 2.07

keywords:
  - math
  - bigint
  - gmp
  - integer

resources:
  homepage                  : http://search.cpan.org/dist/Math-GMP/
  license                   : http://dev.perl.org/licenses/
  bugtracker                : http://rt.cpan.org/Public/Dist/Display.html?Name=Math-GMP

meta-spec:
  version                   : 1.4
  url                       : http://module-build.sourceforge.net/META-spec-v1.4.html

generated_by                : emacs
